<?xml version="1.0" encoding="UTF-8"?>
<ROOT CONV_VERSION="1.2">
<GENERAL>
<UID>time:1223980497131_uuid:75978425-5f60-4ed8-9a81-fa2874c3f654</UID>
<PACKAGE>moin.base</PACKAGE>
<DOMAIN>BC</DOMAIN>
<ORIGLANG>EN</ORIGLANG>
<RESPONSIBLE>D022737</RESPONSIBLE>
</GENERAL>
<RESOURCES>
<TEXT AKEY="PROCESS_ERROR_LOC_XMSG" LENGTH="255" PROCESSOR="MessageFormat" TYPE="XMSG">Error from line {0} and column {1} to line {2} and column {3} : {4}</TEXT>
<TEXT AKEY="PROCESS_ERROR_XMSG" LENGTH="255" PROCESSOR="MessageFormat" TYPE="XMSG">Error : {0}</TEXT>
<TEXT AKEY="PROCESS_EXCEPTION_XMSG" LENGTH="255" PROCESSOR="MessageFormat" TYPE="XMSG">An internal Exception was thrown, original message "{0}"</TEXT>
<TEXT AKEY="PROCESS_REPORT_XMSG" LENGTH="255" PROCESSOR="MessageFormat" TYPE="XMSG">Finished with {0} errors and {1} warnings.</TEXT>
<TEXT AKEY="PROCESS_WARNING_LOC_XMSG" LENGTH="255" PROCESSOR="MessageFormat" TYPE="XMSG">Warning from line {0} and column {1} to line {2} and column {3} : {4}</TEXT>
<TEXT AKEY="PROCESS_WARNING_XMSG" LENGTH="255" PROCESSOR="MessageFormat" TYPE="XMSG">Warning : {0}</TEXT>
</RESOURCES>
</ROOT>
